DROP DATABASE IF EXISTS text_board;
CREATE DATABASE text_board;
USE text_board;

CREATE TABLE article (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	regDate DATETIME NOT NULL,
	updateDate DATETIME NOT NULL,
	title CHAR(20) NOT NULL,
	content TEXT NOT NULL
);